# Generated by Django 5.2.6 on 2025-09-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_is_featured_product_is_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('transfer', 'Transfer'), ('socks', 'Socks'), ('exclusive', 'Exclusive'), ('away', 'Away Jersey'), ('home', 'Home Jersey'), ('third', 'Third Jersey'), ('badges', 'Badges')], default='update', max_length=20),
        ),
    ]
