# Generated by Django 5.2.6 on 2025-10-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('scarves', 'Scarves'), ('socks', 'Socks'), ('accessories', 'Accessories'), ('away', 'Away Jersey'), ('home', 'Home Jersey'), ('third', 'Third Jersey'), ('badges', 'Badges')], default='update', max_length=20),
        ),
    ]
